# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
