# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='count',
            new_name='choice_count',
        ),
    ]
